### ISSUE TITLE
Migrate models to SQLAlchemy v2

### ISSUE THREAD

**Issue by frostming** [bamboo-cms/bamboo#11]
https://github.com/bamboo-cms/bamboo/pull/6#issuecomment-1863051974

Track it here, @yuxiaoy1 would you like to make a PR?

**Comment by yuxiaoy1** [comment]
OK, will PR later.

**Comment by yuxiaoy1** [comment]
PR submitted https://github.com/bamboo-cms/bamboo/pull/12
